### PR TITLE
Basic implementation and basic tests added for using sparsevec introduced in pgvector 0.7.0.

### PR DESCRIPTION
**Pull request by cho-thinkfree-com**
I have written the basic code to use sparsevec added in pgvector 0.7.0. I have confirmed that basic operations are functioning correctly.

Only the part handling Query as String has been implemented, and the part using binary has not been included as I am not aware of how it operates.

### CODE REVIEW

**Comment by cho-thinkfree-com** [comment]
I saw that commit da1e3a5164f0d905e691e11a9c5baf1b4fb21985, which applies the sparsevec feature to the master branch, has been pushed. Therefore, I will close the related Pull Request.

**Comment by ankane** [comment]
Hi @cho-thinkfree-com, thanks for the PR (and sorry for the delay)! I agree a map constructor makes sense, so added in the commit above.

**Comment by cho-thinkfree-com** [comment]
@ankane // I know this is old, but thank you for your review. Just out of curiosity, when are you planning to make a new release? I hope you don't mind me asking, I just want to delete the temporary code :-)

**Comment by ankane** [comment]
Just released 0.1.5

**Comment by cho-thinkfree-com** [comment]
When I removed my temporary class and replaced it with the latest library you posted, everything worked fine.
Thanks for the quick turnaround, I know it must have been a hassle.

**Comment by ankane** [comment]
Great, thanks @cho-thinkfree-com!

**Pull request closed without merging**
